In [4]:
import numpy as np

rng = np.random.default_rng(42)
print(rng)
rng.normal(0, 1, (3, 3))
print(rng)
rng.integers(0, 10, (3, 3))
print(rng)
arr = np.array([1, 2, 3, 4, 5])
rng.shuffle(arr)
print(arr)

Generator(PCG64)
Generator(PCG64)
Generator(PCG64)
[2 1 5 3 4]

In [44]:
import pandas as pd
df = pd.DataFrame({
    'name':   ['Alice', 'Bob', 'Carol', 'Dave'],
    'age':    [1, 30, 35, 28],
    'score':    [1, 30, 35, 28],
    'salary': [70000, 85000, 90000, 75000],
    'dept':   ['Eng', 'Sales', 'Eng', 'HR']
})

In [39]:
df['age_group'] = df['age'].apply(lambda x:
    'young'  if x < 30 else
    'mid'    if x < 45 else
    'senior'
)
df

    name  age  salary   dept age_group
0  Alice    0   70000    Eng     young
1    Bob   30   85000  Sales       mid
2  Carol   35   90000    Eng       mid
3   Dave   28   75000     HR     young

In [46]:
df['value_score'] = df.apply(
    lambda row: row['salary'] / row['age'] * row['score'],
    axis=1    # axis=1 means "apply across columns for each row"
)
df

    name  age  score  salary   dept  value_score
0  Alice    1      1   70000    Eng      70000.0
1    Bob   30     30   85000  Sales      85000.0
2  Carol   35     35   90000    Eng      90000.0
3   Dave   28     28   75000     HR      75000.0

In [8]:
df.head()

    name  age  salary   dept
0  Alice   25   70000    Eng
1    Bob   30   85000  Sales
2  Carol   35   90000    Eng
3   Dave   28   75000     HR

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    4 non-null      str
 1   age     4 non-null      int64
 2   salary  4 non-null      int64
 3   dept    4 non-null      str
dtypes: int64(2), str(2)
memory usage: 260.0 bytes

In [16]:
df.describe()

             age        salary
count   4.000000      4.000000
mean   23.250000  80000.000000
std    15.777093   9128.709292
min     0.000000  70000.000000
25%    21.000000  73750.000000
50%    29.000000  80000.000000
75%    31.250000  86250.000000
max    35.000000  90000.000000

In [17]:
df.isnull().sum()

name      0
age       0
salary    0
dept      0
dtype: int64

In [18]:
df['dept'].value_counts()

dept
Eng      2
Sales    1
HR       1
Name: count, dtype: int64

In [20]:
df.duplicated()

0    False
1    False
2    False
3    False
dtype: bool

In [21]:
df.nunique()

name      4
age       4
salary    4
dept      3
dtype: int64

In [22]:
df.loc[0, 'name']

'Alice'

In [23]:
df.iloc[:, -1]

0      Eng
1    Sales
2      Eng
3       HR
Name: dept, dtype: str

In [24]:
df[(df['age'] > 25) & (df['dept'] == 'Eng')]

    name  age  salary dept
2  Carol   35   90000  Eng

In [25]:
df[(df['dept'] == 'Eng') | (df['dept'] == 'Sales')]

    name  age  salary   dept
0  Alice    0   70000    Eng
1    Bob   30   85000  Sales
2  Carol   35   90000    Eng

In [26]:
df.query("age > 28 and dept == 'Eng'")
df.query("salary > 80000 and dept != 'HR'")

    name  age  salary   dept
1    Bob   30   85000  Sales
2  Carol   35   90000    Eng

In [28]:
df = df.assign(
    tax = df['salary'] * 0.20,
    net = lambda x: x['salary'] - x['tax']   # can reference column just created above
)
df

    name  age  salary   dept      tax      net
0  Alice    0   70000    Eng  14000.0  56000.0
1    Bob   30   85000  Sales  17000.0  68000.0
2  Carol   35   90000    Eng  18000.0  72000.0
3   Dave   28   75000     HR  15000.0  60000.0

In [30]:
df['dept_code'] = df['dept'].map({'Eng': 1, 'Sales': 2, 'HR': 3})
df

    name  age  salary   dept      tax      net  dept_code
0  Alice    0   70000    Eng  14000.0  56000.0          1
1    Bob   30   85000  Sales  17000.0  68000.0          2
2  Carol   35   90000    Eng  18000.0  72000.0          1
3   Dave   28   75000     HR  15000.0  60000.0          3

In [32]:
df.isnull().sum() / len(df)

name         0.0
age          0.0
salary       0.0
dept         0.0
tax          0.0
net          0.0
dept_code    0.0
dtype: float64

In [34]:
df['salary'] = df.groupby('dept')['salary'].transform(
    lambda x: x.fillna(x.median())
)
df

    name  age  salary   dept      tax      net  dept_code
0  Alice    0   70000    Eng  14000.0  56000.0          1
1    Bob   30   85000  Sales  17000.0  68000.0          2
2  Carol   35   90000    Eng  18000.0  72000.0          1
3   Dave   28   75000     HR  15000.0  60000.0          3

In [47]:
import pandas as pd

df_jan = pd.DataFrame({
    'emp_id': [1, 2, 3],
    'dept': ['HR', 'Engineering', 'Sales'],
    'salary': [60000, 120000, 80000]
})

df_feb = pd.DataFrame({
    'emp_id': [4, 5, 6],
    'dept': ['HR', 'Engineering', 'Sales'],
    'salary': [65000, 125000, 82000]
})

df_mar = pd.DataFrame({
    'emp_id': [7, 8, 9],
    'dept': ['HR', 'Engineering', 'Sales'],
    'salary': [62000, 130000, 78000]
})

In [48]:
pd.concat([df_jan, df_feb, df_mar], axis=0, ignore_index=True)
df

    name  age  score  salary   dept  value_score
0  Alice    1      1   70000    Eng      70000.0
1    Bob   30     30   85000  Sales      85000.0
2  Carol   35     35   90000    Eng      90000.0
3   Dave   28     28   75000     HR      75000.0